#!/usr/bin/env bash
# score-lint-pass-rate.sh — emit a `lint-pass-rate` observation for the
# lint-posture dimension, conditional on the consumer repo carrying
# lintguini-managed config.
#
# Gating (M5 conditional-scorer pattern, ADR-008 rubric authority):
#   - empty-scope if no lintguini-marked config is present (no
#     `Generated by lintguini` provenance in pyproject.toml /
#     biome.json (`_provenance`) / rustfmt.toml / standard.yml /
#     .rubocop.yml / .golangci.yml). On non-lintguini consumers this
#     scorer must contribute nothing — A4 of the expansion plan is the
#     load-bearing assertion.
#   - empty-scope (with a stderr notice) if the language's canonical
#     linter is not on PATH. Tool absence is not an audit failure;
#     consumers may not have installed the toolchain yet.
#
# When gated through, the scorer dispatches `bin/lintguini-lint.sh`
# (per-language) against REPO_ROOT, parses the locked
# `path:line:rule:message` finding shape (skipping `# LANG — N findings`
# section headers), and computes per-language pass rate as
#   files_clean / files_scanned
# where files_scanned is the count of source files for the language
# (same find-pattern shape used by score-suppression-count.sh) and
# files_clean = files_scanned - files_with_findings.
#
# Polyglot aggregation: a single observation is emitted with summed
# scanned + clean counts across languages and a `languages` slug list
# in the evidence; the ratio weights by file count by construction.
#
# ADR-006 §2: read-only against REPO_ROOT. The dispatched linter reads
# source files and emits diagnostics — it does not mutate the working
# tree. ADR-008 rule 5: the audit grades against the rubric, not
# against templates; the pass-rate observation is evidence the rubric
# can ladder later (no rubric stanza in 2b3 — observations[] entries
# without a stanza fall through `dropped` cleanly via the translator's
# "no rubric rule registered" branch and do not perturb the composite).
#
# Determinism contract: same REPO_ROOT state + same tool versions on
# PATH → byte-equivalent output. Source-file enumeration is sorted
# under LC_ALL=C; finding-path counting is grep-and-awk deterministic.
#
# Usage:
#   score-lint-pass-rate.sh <REPO_ROOT>
#
# Exit 0 on success or empty-scope. Exit 2 on argument or environment
# errors.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_common.sh
. "$HERE/_common.sh"

PLUGIN_ROOT="$(cd "$HERE/.." && pwd)"
LINT_BIN="$PLUGIN_ROOT/bin/lintguini-lint.sh"

PROVENANCE_MARK='Generated by lintguini'

if [[ $# -ne 1 ]]; then
  echo "Usage: $(basename "$0") <REPO_ROOT>" >&2
  exit 2
fi
REPO_ROOT="$1"
if [[ ! -d "$REPO_ROOT" ]]; then
  echo "Error: REPO_ROOT '$REPO_ROOT' is not a directory" >&2
  exit 2
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "Error: jq required" >&2
  exit 2
fi
if [[ ! -x "$LINT_BIN" ]]; then
  echo "Error: lintguini-lint.sh not executable at $LINT_BIN" >&2
  exit 2
fi

# is_lintguini_configured <lang>
#   Same provenance check used by /lintguini:lint and /lintguini:fix —
#   the marker is the leading-comment / `_provenance` key
#   /lintguini:configure writes into every config it produces.
is_lintguini_configured() {
  local lang="$1"
  case "$lang" in
    python)
      [[ -f "$REPO_ROOT/pyproject.toml" ]] \
        && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/pyproject.toml"
      ;;
    javascript|typescript)
      [[ -f "$REPO_ROOT/biome.json" ]] \
        && jq -e --arg m "$PROVENANCE_MARK" \
            '(._provenance // "") | contains($m)' "$REPO_ROOT/biome.json" >/dev/null 2>&1
      ;;
    rust)
      [[ -f "$REPO_ROOT/rustfmt.toml" ]] \
        && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/rustfmt.toml"
      ;;
    ruby)
      ( [[ -f "$REPO_ROOT/standard.yml" ]] && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/standard.yml" ) \
        || ( [[ -f "$REPO_ROOT/.rubocop.yml" ]] && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/.rubocop.yml" )
      ;;
    go)
      [[ -f "$REPO_ROOT/.golangci.yml" ]] \
        && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/.golangci.yml"
      ;;
    *)
      return 1
      ;;
  esac
}

# canonical_tool <lang>
#   The single linter the rubric pins per language. ruby resolves at
#   runtime based on which provenance-marked config is present (mirrors
#   bin/lintguini-lint.sh's ruby_tool selection).
canonical_tool() {
  case "$1" in
    python)                echo "ruff" ;;
    javascript|typescript) echo "biome" ;;
    rust)                  echo "cargo" ;;
    go)                    echo "golangci-lint" ;;
    ruby)
      if [[ -f "$REPO_ROOT/standard.yml" ]] \
         && grep -F -q "$PROVENANCE_MARK" "$REPO_ROOT/standard.yml" 2>/dev/null; then
        echo "standardrb"
      else
        echo "rubocop"
      fi
      ;;
  esac
}

# enumerate_source_files <lang>
#   Print one absolute source-file path per line for <lang>. Excludes
#   the conventional vendored / build-output directories per language;
#   the find-arg shape mirrors score-suppression-count.sh so the two
#   scorers measure the same denominator.
enumerate_source_files() {
  local lang="$1"
  case "$lang" in
    python)
      find "$REPO_ROOT" -type f -name '*.py' \
        -not -path '*/.venv/*' -not -path '*/venv/*' -not -path '*/__pycache__/*' \
        2>/dev/null
      ;;
    javascript)
      find "$REPO_ROOT" -type f \( \
        -name '*.js' -o -name '*.jsx' -o -name '*.mjs' -o -name '*.cjs' \
        \) \
        -not -path '*/node_modules/*' -not -path '*/dist/*' -not -path '*/build/*' \
        2>/dev/null
      ;;
    typescript)
      find "$REPO_ROOT" -type f \( -name '*.ts' -o -name '*.tsx' \) \
        -not -path '*/node_modules/*' -not -path '*/dist/*' -not -path '*/build/*' \
        2>/dev/null
      ;;
    rust)
      find "$REPO_ROOT" -type f -name '*.rs' -not -path '*/target/*' 2>/dev/null
      ;;
    ruby)
      find "$REPO_ROOT" -type f -name '*.rb' -not -path '*/vendor/bundle/*' 2>/dev/null
      ;;
    go)
      find "$REPO_ROOT" -type f -name '*.go' -not -path '*/vendor/*' 2>/dev/null
      ;;
  esac
}

# Phase 1 — discover lintguini-configured languages. Empty-scope at the
# gate when none are present (the load-bearing A4 invariant: no
# lintguini marker → this scorer contributes nothing).
TARGET_LANGS=()
for lang in python javascript typescript rust ruby go; do
  if is_lintguini_configured "$lang"; then
    TARGET_LANGS+=("$lang")
  fi
done

if [[ ${#TARGET_LANGS[@]} -eq 0 ]]; then
  exit 0
fi

# Phase 2 — tool availability. Empty-scope (with a stderr notice) the
# entire observation if any in-scope language's linter isn't on PATH.
# Partial pass-rate across some-but-not-all configured languages would
# misrepresent the consumer's posture — better to omit cleanly and let
# the consumer install the tool than to land a misleading ratio.
for lang in "${TARGET_LANGS[@]}"; do
  tool="$(canonical_tool "$lang")"
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "Notice: $tool not on PATH; lint-pass-rate omitted (configure $lang installed but tool unavailable)" >&2
    exit 0
  fi
done

# Phase 3 — per-language scan + lint dispatch. Aggregate scanned and
# files-with-findings counts; the pass rate is computed once at the
# end across the totals.
TOTAL_SCANNED=0
TOTAL_WITH_FINDINGS=0
FILES_LIST="$(mktemp -t lintguini-pass-rate-files.XXXXXX)"
FINDINGS_PATHS="$(mktemp -t lintguini-pass-rate-findings.XXXXXX)"
trap 'rm -f "$FILES_LIST" "$FINDINGS_PATHS"' EXIT

ACTIVE_LANGS=()
for lang in "${TARGET_LANGS[@]}"; do
  enumerate_source_files "$lang" | LC_ALL=C sort -u > "$FILES_LIST"
  scanned=$(wc -l < "$FILES_LIST" | tr -d ' ')
  scanned=${scanned:-0}
  if (( scanned == 0 )); then
    # configured but no source files of this language present in the
    # tree — skip this language without contributing to the denominator.
    continue
  fi

  # Dispatch the per-language linter. lintguini-lint exits 0 (clean), 1
  # (findings), 3 (tool missing), 4 (parse failure). 0 and 1 produce
  # findings on stdout; treat anything else as fatal so we don't grade
  # against a corrupted reading.
  out=""
  rc=0
  out="$("$LINT_BIN" --language "$lang" "$REPO_ROOT" 2>/dev/null)" || rc=$?
  if (( rc != 0 && rc != 1 )); then
    echo "Notice: lintguini-lint failed for $lang (exit $rc); lint-pass-rate omitted" >&2
    exit 0
  fi

  # Section-header lines start with `# `; the lint contract pins them
  # as the only non-finding lines on stdout. Per-language dispatch via
  # --language emits no header (single-language run), but be defensive.
  with_findings=0
  if [[ -n "$out" ]]; then
    : >"$FINDINGS_PATHS"
    printf '%s\n' "$out" \
      | grep -v '^#' \
      | grep -v '^[[:space:]]*$' \
      | awk -F: '{print $1}' \
      | LC_ALL=C sort -u >"$FINDINGS_PATHS"
    with_findings=$(wc -l < "$FINDINGS_PATHS" | tr -d ' ')
    with_findings=${with_findings:-0}
  fi

  # Defensive cap: a finding path outside the enumerated source set
  # shouldn't inflate the dirty count above the denominator. (This can
  # happen when a tool reports against a generated file the find-pattern
  # excludes.) Cap at scanned so the per-language ratio stays in [0,1].
  if (( with_findings > scanned )); then
    with_findings=$scanned
  fi

  TOTAL_SCANNED=$((TOTAL_SCANNED + scanned))
  TOTAL_WITH_FINDINGS=$((TOTAL_WITH_FINDINGS + with_findings))
  ACTIVE_LANGS+=("$lang")
done

# Phase 4 — emit. If every configured language had zero source files,
# empty-scope: there's nothing to grade.
if (( TOTAL_SCANNED == 0 )); then
  exit 0
fi

FILES_CLEAN=$((TOTAL_SCANNED - TOTAL_WITH_FINDINGS))
RATIO=$(format_ratio "$FILES_CLEAN" "$TOTAL_SCANNED")

# Stable, deterministic language slug list for the evidence — sorted
# by the iteration order above (rubric order: python, javascript,
# typescript, rust, ruby, go), which is stable across runs because
# TARGET_LANGS is built in the same fixed order.
LANGS_JSON=$(printf '%s\n' "${ACTIVE_LANGS[@]}" \
  | jq -R . | jq -s .)

# Summary text: "<clean>/<scanned> files clean across <langs>".
LANGS_CSV=$(printf '%s, ' "${ACTIVE_LANGS[@]}")
LANGS_CSV=${LANGS_CSV%, }

jq -nc \
  --argjson scanned "$TOTAL_SCANNED" \
  --argjson clean "$FILES_CLEAN" \
  --argjson ratio "$RATIO" \
  --argjson langs "$LANGS_JSON" \
  --arg langs_csv "$LANGS_CSV" \
  '{
    id: "lint-pass-rate",
    kind: "ratio",
    evidence: {
      files_scanned: $scanned,
      files_clean: $clean,
      ratio: $ratio,
      languages: $langs
    },
    summary: "\($clean)/\($scanned) files clean across \($langs_csv)"
  }'
