#!/usr/bin/env bash
# audit-a4-regression.test.sh — A4 regression test from the
# lintguini-expansion plan. The load-bearing assertion: T5's
# conditional scorers must not regress non-lintguini consumers.
#
# Plan (mirrors inkwell's audit-a4-regression pattern verbatim): run
# `bin/build-envelope.sh` against a lintguini-marked fixture AND
# against a derived "plain" copy with the lintguini provenance
# comment stripped from every config file. Diff the four pre-T5
# scorers' observations across the two envelopes:
#
#   - linter-strictness-ratio
#   - formatter-configured-count
#   - ci-lint-wired-ratio
#   - lint-suppression-count
#
# These must be byte-equivalent across both runs because the only
# delta between the two fixtures is the lintguini self-describing
# comment that the legacy scorers are blind to (they read TOML
# tables, glob CI surfaces, and grep source files — none of them
# read the leading config comment). The new T5 conditional scorer
# (lint-pass-rate) appears ONLY on the marked side and is absent on
# the plain side.
#
# Deriving the plain fixture from the marked one at test time —
# rather than maintaining two parallel blueprints — is what keeps
# the byte-equivalence assertion honest: there is no opportunity for
# fixture drift to mask a regression.
#
# Determinism: the dispatched linter is mocked (a fake `ruff` on
# PATH that emits known JSON), so the test runs the same on any box
# regardless of what real toolchain is installed.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
ENVELOPE="$PLUGIN_ROOT/bin/build-envelope.sh"
BLUEPRINT="$HERE/fixtures/audit-a4/blueprint"
fail=0

assert_eq() {
  local label="$1" expected="$2" actual="$3"
  if [[ "$actual" != "$expected" ]]; then
    echo "FAIL [$label]: expected '$expected', got '$actual'" >&2
    fail=1
  fi
}

# Pre-T5 ("legacy") observation IDs. Their presence + content must be
# byte-equivalent across marked + plain — the only delta between the
# two fixtures is the provenance comment, and the legacy scorers do
# not read that comment.
LEGACY_IDS=(
  "linter-strictness-ratio"
  "formatter-configured-count"
  "ci-lint-wired-ratio"
  "lint-suppression-count"
)

# T5 conditional observation IDs. These must appear only on the
# lintguini-marked side and be absent on the plain side.
CONDITIONAL_IDS=(
  "lint-pass-rate"
)

# strip_lintguini_provenance <repo-dir>
#   For every file lintguini's /lintguini:configure plants a marker
#   into, drop the leading "Generated by lintguini" comment line. For
#   biome.json (which carries provenance as a `_provenance` JSON key),
#   drop that key. This is the inverse of the lintguini-configure
#   marker contract — running it produces a config tree as if a
#   non-lintguini author had written the same content.
strip_lintguini_provenance() {
  local dir="$1" tmp
  for f in pyproject.toml rustfmt.toml standard.yml .rubocop.yml .golangci.yml; do
    [[ -f "$dir/$f" ]] || continue
    tmp="$(mktemp)"
    grep -v '^# Generated by lintguini' "$dir/$f" > "$tmp" || true
    mv "$tmp" "$dir/$f"
  done
  if [[ -f "$dir/biome.json" ]]; then
    tmp="$(mktemp)"
    jq 'del(._provenance) | del(._band)' "$dir/biome.json" > "$tmp"
    mv "$tmp" "$dir/biome.json"
  fi
}

# Mock ruff that emits a single finding against src/dirty.py. The
# scorer parses the locked path:line:rule:message shape; on the
# marked side this surfaces as files_clean=1, files_scanned=2,
# ratio=0.5. On the plain side the conditional self-gates and ruff
# is never invoked.
make_mock_bin() {
  local mb="$1"
  cat > "$mb/ruff" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
[
  {"filename": "src/dirty.py", "code": "F401", "message": "imported but unused: os", "location": {"row": 1, "column": 1}}
]
JSON
exit 1
MOCK
  chmod +x "$mb/ruff"
}

MARKED_REPO="$(mktemp -d -t lintguini-a4-marked.XXXXXX)"
PLAIN_REPO="$(mktemp -d -t lintguini-a4-plain.XXXXXX)"
MOCK_BIN="$(mktemp -d -t lintguini-a4-mockbin.XXXXXX)"
trap 'rm -rf "$MARKED_REPO" "$PLAIN_REPO" "$MOCK_BIN"' EXIT

cp -r "$BLUEPRINT"/. "$MARKED_REPO"/
cp -r "$BLUEPRINT"/. "$PLAIN_REPO"/
strip_lintguini_provenance "$PLAIN_REPO"
make_mock_bin "$MOCK_BIN"

# Sanity-check the derivation: pyproject.toml in marked must contain
# the provenance line; plain must not. If this check fails, the
# strip_lintguini_provenance helper is broken and the rest of the
# test would silently pass against a non-derived plain fixture —
# defeating the load-bearing A4 assertion.
if ! grep -q '^# Generated by lintguini' "$MARKED_REPO/pyproject.toml"; then
  echo "FAIL [derivation sanity]: marked fixture missing provenance comment" >&2
  fail=1
fi
if grep -q '^# Generated by lintguini' "$PLAIN_REPO/pyproject.toml"; then
  echo "FAIL [derivation sanity]: plain fixture still carries provenance comment" >&2
  fail=1
fi

MARKED_ENV="$(PATH="$MOCK_BIN:$PATH" "$ENVELOPE" "$MARKED_REPO")"
PLAIN_ENV="$( PATH="$MOCK_BIN:$PATH" "$ENVELOPE" "$PLAIN_REPO")"

# ---------------------------------------------------------------------
# A4 #1: legacy scorer observations are byte-equivalent across
# fixtures. The only delta between marked and plain is the lintguini
# provenance comment, and the four legacy scorers don't read that
# comment.
# ---------------------------------------------------------------------

for id in "${LEGACY_IDS[@]}"; do
  marked_obs="$(echo "$MARKED_ENV" | jq -c --arg id "$id" '.observations[] | select(.id == $id)')"
  plain_obs="$( echo "$PLAIN_ENV"  | jq -c --arg id "$id" '.observations[] | select(.id == $id)')"
  assert_eq "legacy scorer '$id' byte-equivalent" "$plain_obs" "$marked_obs"
done

# ---------------------------------------------------------------------
# A4 #2: T5 conditional scorers fire only on the marked side.
# ---------------------------------------------------------------------

for id in "${CONDITIONAL_IDS[@]}"; do
  marked_present="$(echo "$MARKED_ENV" | jq -r --arg id "$id" '[.observations[] | select(.id == $id)] | length > 0')"
  plain_present="$( echo "$PLAIN_ENV"  | jq -r --arg id "$id" '[.observations[] | select(.id == $id)] | length > 0')"
  assert_eq "conditional '$id' present on marked"  "true"  "$marked_present"
  assert_eq "conditional '$id' absent on plain"    "false" "$plain_present"
done

# ---------------------------------------------------------------------
# A4 #3: composite envelope shape is unchanged on the plain side
# (schema_version, plugin, dimension, composite_score all match the
# pre-T5 envelope shape).
# ---------------------------------------------------------------------

assert_eq "plain schema_version"  "2"             "$(echo "$PLAIN_ENV" | jq -r '."$schema_version"')"
assert_eq "plain plugin"          "lintguini"     "$(echo "$PLAIN_ENV" | jq -r '.plugin')"
assert_eq "plain dimension"       "lint-posture"  "$(echo "$PLAIN_ENV" | jq -r '.dimension')"
assert_eq "plain composite_score" "null"          "$(echo "$PLAIN_ENV" | jq -r '.composite_score')"

# Plain side observation count matches the pre-T5 contract (4).
assert_eq "plain observations count" "4" "$(echo "$PLAIN_ENV" | jq -r '.observations | length')"

# ---------------------------------------------------------------------
# A4 #4: lint-pass-rate evidence on the marked side projects from the
# mock ruff's known finding. files_scanned=2 (src/clean.py +
# src/dirty.py), files_clean=1 (src/clean.py only — dirty has the
# mock finding), ratio=0.5000.
# ---------------------------------------------------------------------

PR="$(echo "$MARKED_ENV" | jq -c '.observations[] | select(.id == "lint-pass-rate")')"
assert_eq "lint-pass-rate files_scanned" "2"      "$(echo "$PR" | jq -r '.evidence.files_scanned')"
assert_eq "lint-pass-rate files_clean"   "1"      "$(echo "$PR" | jq -r '.evidence.files_clean')"
assert_eq "lint-pass-rate ratio"         "0.5000" "$(echo "$PR" | jq -r '.evidence.ratio')"
assert_eq "lint-pass-rate languages"     '["python"]' "$(echo "$PR" | jq -c '.evidence.languages')"

if (( fail == 0 )); then
  echo "audit-a4-regression.test.sh: PASS"
  exit 0
else
  echo "audit-a4-regression.test.sh: FAIL" >&2
  exit 1
fi
