#!/usr/bin/env bash
# configure.test.sh — exercise bin/lintguini-configure.sh end-to-end
# across every rubric language plus the cross-cutting concerns the M2
# brief calls out: TOML merge correctness, ruby auto-detection,
# idempotency, re-banding, CI wiring, --dry-run, and triple-run
# determinism.
#
# Tests run against tempdir fixtures built ad-hoc per case (the
# scorers/tests/fixtures/ tree is hand-curated for the audit path
# and would mix concerns if reused for write-test fixtures). Each
# tempdir is cleaned via per-case trap so failures don't leave the
# host's /tmp littered.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="$PLUGIN_ROOT/bin/lintguini-configure.sh"

PASS=0
FAIL=0
FAILURES=()

note_pass() { PASS=$((PASS + 1)); }
note_fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
}

if [[ ! -x "$SCRIPT" ]]; then
  echo "FATAL: $SCRIPT not executable" >&2
  exit 2
fi

PROVENANCE='Generated by lintguini — see plugins/pronto/references/roll-your-own/lint-posture.md for the source of truth.'

# mktmp_repo  — make a tempdir, register cleanup via the global TRAP
# accumulator, return the path.
TMPROOT="$(mktemp -d -t lintguini-configure-tests.XXXXXX)"
trap 'rm -rf "$TMPROOT"' EXIT

mktmp_repo() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "$1.XXXXXX")"
  printf '%s' "$d"
}

run_configure() {
  bash "$SCRIPT" "$@" 2>&1
}

# -- 1. Per-language fresh-repo round-trip --------------------------------

# 1a. Python — dry-run preview, then live write, then idempotency.
test_python_round_trip() {
  local repo; repo="$(mktmp_repo py)"
  cat > "$repo/pyproject.toml" <<'EOF'
[project]
name = "demo"
version = "0.0.1"
EOF
  local dry; dry="$(run_configure --language python --strict --dry-run "$repo")"
  if [[ "$dry" == *"would updated pyproject.toml"* ]]; then note_pass
  else note_fail "python dry-run: expected 'would updated pyproject.toml', got: $dry"; fi
  # Dry-run must not touch the working tree.
  if [[ "$(cat "$repo/pyproject.toml")" == "[project]"* ]]; then note_pass
  else note_fail "python dry-run mutated working tree"; fi

  local live; live="$(run_configure --language python --strict "$repo")"
  if [[ "$live" == *"updated pyproject.toml"* ]]; then note_pass
  else note_fail "python live: expected 'updated pyproject.toml', got: $live"; fi

  # Provenance is the first non-blank line.
  local first; first="$(awk 'NF { sub(/^[[:space:]]+/, ""); print; exit }' "$repo/pyproject.toml")"
  if [[ "$first" == "# $PROVENANCE" ]]; then note_pass
  else note_fail "python provenance not first non-blank line: '$first'"; fi

  local rerun; rerun="$(run_configure --language python --strict "$repo")"
  if [[ "$rerun" == *"skipped pyproject.toml (already configured)"* ]]; then note_pass
  else note_fail "python idempotency: expected skipped, got: $rerun"; fi
}

# 1b. JavaScript — fresh write of biome.json, then idempotency.
test_javascript_round_trip() {
  local repo; repo="$(mktmp_repo js)"
  echo '{"name":"demo"}' > "$repo/package.json"

  local live; live="$(run_configure --language javascript --strict "$repo")"
  if [[ "$live" == *"wrote biome.json"* ]]; then note_pass
  else note_fail "js fresh write: expected 'wrote biome.json', got: $live"; fi

  local first_key; first_key="$(jq -r 'keys_unsorted[0] // ""' "$repo/biome.json")"
  if [[ "$first_key" == "_provenance" ]]; then note_pass
  else note_fail "js _provenance not first key: '$first_key'"; fi

  local rerun; rerun="$(run_configure --language javascript --strict "$repo")"
  if [[ "$rerun" == *"skipped biome.json (already configured)"* ]]; then note_pass
  else note_fail "js idempotency: expected skipped, got: $rerun"; fi
}

# 1c. TypeScript — biome.json + tsconfig.json.
test_typescript_round_trip() {
  local repo; repo="$(mktmp_repo ts)"
  echo '{"name":"demo"}' > "$repo/package.json"
  echo '{"compilerOptions":{"target":"ES2020"},"include":["src/**/*"]}' > "$repo/tsconfig.json"

  local live; live="$(run_configure --language typescript --strict "$repo")"
  if [[ "$live" == *"wrote biome.json"* && "$live" == *"updated tsconfig.json"* ]]; then note_pass
  else note_fail "ts: expected biome wrote + tsconfig updated, got: $live"; fi

  # tsconfig's preserved key must survive.
  local include; include="$(jq -r '.include[0]' "$repo/tsconfig.json")"
  if [[ "$include" == "src/**/*" ]]; then note_pass
  else note_fail "ts merge dropped 'include' key: $include"; fi

  # tsconfig _provenance first.
  local first_key; first_key="$(jq -r 'keys_unsorted[0] // ""' "$repo/tsconfig.json")"
  if [[ "$first_key" == "_provenance" ]]; then note_pass
  else note_fail "ts tsconfig _provenance not first key: '$first_key'"; fi

  local rerun; rerun="$(run_configure --language typescript --strict "$repo")"
  if [[ "$rerun" == *"skipped biome.json (already configured)"* \
      && "$rerun" == *"skipped tsconfig.json (already configured)"* ]]; then note_pass
  else note_fail "ts idempotency: expected skipped both, got: $rerun"; fi
}

# 1d. Rust — rustfmt.toml direct + Cargo.toml merge with [lints*].
test_rust_round_trip() {
  local repo; repo="$(mktmp_repo rust)"
  cat > "$repo/Cargo.toml" <<'EOF'
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
EOF

  local live; live="$(run_configure --language rust --strict "$repo")"
  if [[ "$live" == *"wrote rustfmt.toml"* && "$live" == *"updated Cargo.toml"* ]]; then note_pass
  else note_fail "rust: expected rustfmt wrote + Cargo updated, got: $live"; fi

  # Preserved [package] section must remain.
  if grep -q '^\[package\]' "$repo/Cargo.toml" && grep -q '^name = "demo"' "$repo/Cargo.toml"; then
    note_pass
  else
    note_fail "rust merge: lost user's [package] section"
  fi

  # Fragment landed.
  if grep -q '^\[lints.rust\]' "$repo/Cargo.toml" && grep -q '^\[lints.clippy\]' "$repo/Cargo.toml"; then
    note_pass
  else
    note_fail "rust merge: [lints.*] sections missing from Cargo.toml"
  fi

  # rustfmt.toml provenance first.
  local first; first="$(awk 'NF { sub(/^[[:space:]]+/, ""); print; exit }' "$repo/rustfmt.toml")"
  if [[ "$first" == "# $PROVENANCE" ]]; then note_pass
  else note_fail "rust rustfmt provenance not first line: '$first'"; fi

  local rerun; rerun="$(run_configure --language rust --strict "$repo")"
  if [[ "$rerun" == *"skipped rustfmt.toml (already configured)"* \
      && "$rerun" == *"skipped Cargo.toml (already configured)"* ]]; then note_pass
  else note_fail "rust idempotency: expected skipped both, got: $rerun"; fi
}

# 1e. Ruby — auto-detect rubocop (Gemfile without 'standard').
test_ruby_round_trip_rubocop() {
  local repo; repo="$(mktmp_repo ruby-rubocop)"
  cat > "$repo/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "rails"
EOF

  local live; live="$(run_configure --language ruby --strict "$repo")"
  if [[ "$live" == *"wrote .rubocop.yml"* ]]; then note_pass
  else note_fail "ruby auto-rubocop: expected '.rubocop.yml wrote', got: $live"; fi
  if [[ ! -f "$repo/standard.yml" ]]; then note_pass
  else note_fail "ruby auto-rubocop: should not write standard.yml"; fi

  local rerun; rerun="$(run_configure --language ruby --strict "$repo")"
  if [[ "$rerun" == *"skipped .rubocop.yml (already configured)"* ]]; then note_pass
  else note_fail "ruby auto-rubocop idempotency: $rerun"; fi
}

# 1f. Go — direct copy.
test_go_round_trip() {
  local repo; repo="$(mktmp_repo go)"
  cat > "$repo/go.mod" <<'EOF'
module example.com/demo
go 1.22
EOF

  local live; live="$(run_configure --language go --strict "$repo")"
  if [[ "$live" == *"wrote .golangci.yml"* ]]; then note_pass
  else note_fail "go: expected '.golangci.yml wrote', got: $live"; fi

  local rerun; rerun="$(run_configure --language go --strict "$repo")"
  if [[ "$rerun" == *"skipped .golangci.yml (already configured)"* ]]; then note_pass
  else note_fail "go idempotency: $rerun"; fi
}

# -- 2. TOML merge correctness — pyproject.toml's non-ruff sections survive

test_toml_merge_correctness() {
  local repo; repo="$(mktmp_repo py-merge)"
  cat > "$repo/pyproject.toml" <<'EOF'
[tool.poetry]
name = "demo"
version = "0.1.0"
description = "demo project"

[tool.poetry.dependencies]
python = "^3.12"
EOF

  run_configure --language python --strict "$repo" >/dev/null

  if grep -q '^\[tool\.poetry\]' "$repo/pyproject.toml" \
     && grep -q '^\[tool\.poetry\.dependencies\]' "$repo/pyproject.toml" \
     && grep -q 'description = "demo project"' "$repo/pyproject.toml"; then
    note_pass
  else
    note_fail "TOML merge dropped non-ruff [tool.poetry*] sections"
  fi

  if grep -q '^\[tool\.ruff\]' "$repo/pyproject.toml" \
     && grep -q '^\[tool\.ruff\.lint\]' "$repo/pyproject.toml"; then
    note_pass
  else
    note_fail "TOML merge: [tool.ruff*] sections not landed"
  fi

  # Strict band marker present, no leftover lenient/minimal markers.
  if grep -q '^# Strict band' "$repo/pyproject.toml" \
     && ! grep -q '^# Lenient band' "$repo/pyproject.toml" \
     && ! grep -q '^# Minimal band' "$repo/pyproject.toml"; then
    note_pass
  else
    note_fail "TOML merge: band marker mismatch"
  fi
}

# -- 3. Ruby auto-detection — Gemfile mentions standard ------------------

test_ruby_auto_standardrb() {
  local repo; repo="$(mktmp_repo ruby-auto-standard)"
  cat > "$repo/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "rails"
gem "standard", require: false
EOF

  local live; live="$(run_configure --language ruby --strict "$repo")"
  if [[ "$live" == *"wrote standard.yml"* ]]; then note_pass
  else note_fail "ruby auto-standardrb: expected 'standard.yml wrote', got: $live"; fi
  if [[ ! -f "$repo/.rubocop.yml" ]]; then note_pass
  else note_fail "ruby auto-standardrb: should not write .rubocop.yml"; fi
}

# --ruby-tool override flips the path.
test_ruby_tool_override() {
  local repo; repo="$(mktmp_repo ruby-override)"
  cat > "$repo/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "rails"
EOF
  # Gemfile-default is rubocop; --ruby-tool standardrb overrides.
  run_configure --language ruby --strict --ruby-tool standardrb "$repo" >/dev/null
  if [[ -f "$repo/standard.yml" && ! -f "$repo/.rubocop.yml" ]]; then note_pass
  else note_fail "--ruby-tool standardrb override didn't take effect"; fi
}

# -- 4. Idempotency — back-to-back identical invocations no-op -----------

test_idempotency_back_to_back() {
  local repo; repo="$(mktmp_repo idem)"
  cat > "$repo/pyproject.toml" <<'EOF'
[project]
name = "demo"
EOF
  run_configure --language python --strict "$repo" >/dev/null
  local out2; out2="$(run_configure --language python --strict "$repo")"
  local out3; out3="$(run_configure --language python --strict "$repo")"
  if [[ "$out2" == *"skipped pyproject.toml (already configured)"* \
      && "$out3" == *"skipped pyproject.toml (already configured)"* ]]; then note_pass
  else note_fail "idempotency: second/third runs not skipped. out2='$out2' out3='$out3'"; fi
}

# -- 5. Re-band — strict -> lenient rewrites the band -------------------

test_reband() {
  local repo; repo="$(mktmp_repo reband)"
  cat > "$repo/pyproject.toml" <<'EOF'
[project]
name = "demo"
EOF
  run_configure --language python --strict "$repo" >/dev/null

  local out; out="$(run_configure --language python --lenient "$repo")"
  if [[ "$out" == *"updated pyproject.toml"* ]]; then note_pass
  else note_fail "re-band: expected 'updated pyproject.toml', got: $out"; fi

  if grep -q '^# Lenient band' "$repo/pyproject.toml" \
     && ! grep -q '^# Strict band' "$repo/pyproject.toml"; then
    note_pass
  else
    note_fail "re-band: band marker did not flip strict -> lenient"
  fi

  # Lenient ruff select is shorter.
  if grep -q 'select = \["E", "F", "I"\]' "$repo/pyproject.toml"; then note_pass
  else note_fail "re-band: lenient ruff select not present"; fi

  # Round-trip back to strict, then minimal — every step idempotent on
  # the next run. (Catches preamble-strip leaks.)
  run_configure --language python --strict "$repo"   >/dev/null
  run_configure --language python --minimal "$repo"  >/dev/null
  out="$(run_configure --language python --minimal "$repo")"
  if [[ "$out" == *"skipped pyproject.toml (already configured)"* ]]; then note_pass
  else note_fail "re-band cycle: post-minimal idempotency leak: $out"; fi
}

# -- 6. CI wiring --------------------------------------------------------

test_ci_github_actions() {
  local repo; repo="$(mktmp_repo ci-gh)"
  echo '{"name":"x"}' > "$repo/package.json"
  mkdir -p "$repo/.github/workflows"
  echo 'name: ci' > "$repo/.github/workflows/test.yml"

  local live; live="$(run_configure --language javascript --strict --ci "$repo")"
  if [[ "$live" == *"wrote .github/workflows/lintguini-lint.yml"* ]]; then note_pass
  else note_fail "ci-gh: expected workflow wrote, got: $live"; fi

  if grep -q '^name: lint$' "$repo/.github/workflows/lintguini-lint.yml" \
     && grep -q 'biome check' "$repo/.github/workflows/lintguini-lint.yml"; then
    note_pass
  else
    note_fail "ci-gh: workflow content missing name or lint step"
  fi

  local rerun; rerun="$(run_configure --language javascript --strict --ci "$repo")"
  if [[ "$rerun" == *"skipped .github/workflows/lintguini-lint.yml (already configured)"* ]]; then note_pass
  else note_fail "ci-gh idempotency: $rerun"; fi
}

test_ci_no_surface_warns() {
  local repo; repo="$(mktmp_repo ci-none)"
  echo '{"name":"x"}' > "$repo/package.json"

  # Capture stderr separately from stdout for the warning shape check.
  local stderr_capture
  stderr_capture="$(bash "$SCRIPT" --language javascript --strict --ci "$repo" 2>&1 1>/dev/null)"
  if [[ "$stderr_capture" == *"warning no CI surface detected"* ]]; then note_pass
  else note_fail "ci-none: expected warning on stderr, got: $stderr_capture"; fi

  if [[ -f "$repo/biome.json" ]]; then note_pass
  else note_fail "ci-none: biome.json should still be written without --ci"; fi
}

# -- 7. --dry-run never writes ------------------------------------------

test_dry_run_no_writes() {
  local repo; repo="$(mktmp_repo dryrun)"
  cat > "$repo/pyproject.toml" <<'EOF'
[project]
name = "demo"
EOF
  echo '{"name":"x"}' > "$repo/package.json"
  mkdir -p "$repo/.github/workflows"
  echo 'name: ci' > "$repo/.github/workflows/test.yml"

  # Snapshot pre-state.
  local pre_snapshot
  pre_snapshot="$(cd "$repo" && find . -type f | LC_ALL=C sort | xargs -I{} sha256sum {} 2>/dev/null)"

  run_configure --strict --ci --dry-run "$repo" >/dev/null

  local post_snapshot
  post_snapshot="$(cd "$repo" && find . -type f | LC_ALL=C sort | xargs -I{} sha256sum {} 2>/dev/null)"

  if [[ "$pre_snapshot" == "$post_snapshot" ]]; then note_pass
  else note_fail "--dry-run: working tree mutated"; fi
}

# -- 8. Triple-run determinism on dry-run output -------------------------

test_triple_run_determinism() {
  local repo; repo="$(mktmp_repo determinism)"
  cat > "$repo/pyproject.toml" <<'EOF'
[project]
name = "demo"
EOF
  local r1 r2 r3
  r1="$(run_configure --language python --strict --dry-run "$repo")"
  r2="$(run_configure --language python --strict --dry-run "$repo")"
  r3="$(run_configure --language python --strict --dry-run "$repo")"
  if [[ "$r1" == "$r2" && "$r2" == "$r3" ]]; then note_pass
  else note_fail "triple-run dry-run output diverged"; fi
}

# -- 9. Argument errors --------------------------------------------------

test_argument_errors() {
  local repo; repo="$(mktmp_repo args)"
  echo '{"name":"x"}' > "$repo/package.json"

  bash "$SCRIPT" --strict --lenient --language javascript "$repo" >/dev/null 2>&1
  local rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "mutually-exclusive flags: expected rc=2 got rc=$rc"; fi

  bash "$SCRIPT" --language ruby "$repo" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "--language not detected: expected rc=2 got rc=$rc"; fi

  bash "$SCRIPT" --language elixir "$repo" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "unknown --language: expected rc=2 got rc=$rc"; fi

  bash "$SCRIPT" --strict "$repo/does-not-exist" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "non-existent REPO_ROOT: expected rc=2 got rc=$rc"; fi
}

# -- run -----------------------------------------------------------------

test_python_round_trip
test_javascript_round_trip
test_typescript_round_trip
test_rust_round_trip
test_ruby_round_trip_rubocop
test_go_round_trip
test_toml_merge_correctness
test_ruby_auto_standardrb
test_ruby_tool_override
test_idempotency_back_to_back
test_reband
test_ci_github_actions
test_ci_no_surface_warns
test_dry_run_no_writes
test_triple_run_determinism
test_argument_errors

if (( FAIL == 0 )); then
  echo "configure.test.sh: PASS — $PASS checks"
  exit 0
else
  echo "configure.test.sh: FAIL — $PASS passed, $FAIL failed" >&2
  for msg in "${FAILURES[@]}"; do
    echo "  - $msg" >&2
  done
  exit 1
fi
