#!/usr/bin/env bash
# fix.test.sh — exercise bin/lintguini-fix.sh end-to-end against mocked
# fix tools on PATH. The contract under test is the dispatch logic and
# output projection across read-only / --apply / --apply-semantic
# modes, NOT the fixers themselves. Mocks emit known native output;
# the script's job is to (a) call the right tool with the right flags
# per mode, (b) project output to the contract shape, (c) handle
# empty-scope and tool-missing.
#
# Real fix tools (ruff, biome, cargo, rubocop, standardrb, gofmt) are
# not installed on the test box. Each test stages a tempdir on PATH
# containing a fake binary that branches on argv to emit per-mode
# output, then verifies the script's projection.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="$PLUGIN_ROOT/bin/lintguini-fix.sh"

PASS=0
FAIL=0
FAILURES=()

note_pass() { PASS=$((PASS + 1)); }
note_fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
}

if [[ ! -x "$SCRIPT" ]]; then
  echo "FATAL: $SCRIPT not executable" >&2
  exit 2
fi

PROVENANCE='Generated by lintguini — see plugins/pronto/references/roll-your-own/lint-posture.md for the source of truth.'

TMPROOT="$(mktemp -d -t lintguini-fix-tests.XXXXXX)"
trap 'rm -rf "$TMPROOT"' EXIT

mktmp_repo() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "$1.XXXXXX")"
  printf '%s' "$d"
}

mktmp_mockbin() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "mockbin.XXXXXX")"
  printf '%s' "$d"
}

# -- Provenance-marked config writers (mirror lint/format tests) --------

write_python_config() {
  cat > "$1/pyproject.toml" <<EOF
# $PROVENANCE
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
EOF
}

write_javascript_config() {
  cat > "$1/biome.json" <<EOF
{
  "_provenance": "$PROVENANCE",
  "_band": "strict",
  "\$schema": "https://biomejs.dev/schemas/latest/schema.json",
  "linter": { "enabled": true },
  "formatter": { "enabled": true, "indentWidth": 2 }
}
EOF
  echo '{"name":"demo"}' > "$1/package.json"
}

write_ruby_standardrb_config() {
  cat > "$1/standard.yml" <<EOF
# $PROVENANCE
ruby_version: 3.3
EOF
  cat > "$1/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "standard"
EOF
}

# -- Mocks --------------------------------------------------------------
#
# Each mock branches on argv to handle the modes lintguini-fix dispatches:
#   - check --fix --diff       -> safe-fix preview (read-only mode)
#   - check --fix              -> safe-fix apply
#   - check --fix --unsafe-fixes --diff -> unsafe-fix preview (semantic)
#   - check --write [--unsafe] -> biome's apply / unsafe-apply
#
# Diff blobs use the contract's a/<path> / b/<path> shape so the
# script's normalize_diff is a no-op for these tests; the production
# normalization is exercised via ruff's bare-path output in test 1b.

mock_ruff_safe_diff() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
case "$*" in
  *check*--fix*--unsafe-fixes*--diff*)
    cat <<'DIFF'
--- a/src/x.py
+++ b/src/x.py
@@ -1,3 +1,1 @@
-def dead():
-    pass
-
DIFF
    exit 1 ;;
  *check*--fix*--diff*)
    cat <<'DIFF'
--- a/src/x.py
+++ b/src/x.py
@@ -1,2 +1,2 @@
-import os, sys
+import os
+import sys
DIFF
    exit 1 ;;
  *check*--fix*)
    exit 0 ;;
  *)
    exit 0 ;;
esac
MOCK
  chmod +x "$1/ruff"
}

# Bare-path diff (no a/ b/ prefix) — exercises normalize_diff.
mock_ruff_bare_diff() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
case "$*" in
  *check*--fix*--diff*)
    cat <<'DIFF'
--- src/x.py
+++ src/x.py
@@ -1,1 +1,1 @@
-x=1
+x = 1
DIFF
    exit 1 ;;
  *check*--fix*) exit 0 ;;
esac
MOCK
  chmod +x "$1/ruff"
}

mock_ruff_clean() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
  chmod +x "$1/ruff"
}

# Mock biome that mutates files in cwd when invoked with --write.
# Exercises copy_and_diff: lintguini-fix snapshots REPO_ROOT, runs biome
# in the snapshot, the mock writes to the snapshot, then the script
# diffs the original against the snapshot and emits the result.
mock_biome_writes() {
  local mb="$1" semantic_marker="${2:-}"
  cat > "$mb/biome" <<MOCK
#!/usr/bin/env bash
case "\$*" in
  *check*--write*--unsafe*)
    if [[ -f src/render.js ]]; then
      printf 'const semantic_fix = true;\n' > src/render.js
    fi
    exit 0 ;;
  *check*--write*)
    if [[ -f src/render.js ]]; then
      printf 'const safe_fix = true;\n' > src/render.js
    fi
    exit 0 ;;
  *) exit 0 ;;
esac
MOCK
  chmod +x "$mb/biome"
}

mock_biome_clean() {
  cat > "$1/biome" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
  chmod +x "$1/biome"
}

mock_standardrb_anything() {
  cat > "$1/standardrb" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
  chmod +x "$1/standardrb"
}

# -- Runners ------------------------------------------------------------

run_fix_split() {
  local repo="$1" mockbin="$2"; shift 2
  local out_f="$TMPROOT/out.$$" err_f="$TMPROOT/err.$$"
  PATH="$mockbin:$PATH" bash "$SCRIPT" "$@" "$repo" >"$out_f" 2>"$err_f"
  local rc=$?
  STDOUT="$(cat "$out_f")"
  STDERR="$(cat "$err_f")"
  rm -f "$out_f" "$err_f"
  return $rc
}

# -- 1. Configured + safe-fixable + read-only ---------------------------

test_python_readonly_diff() {
  local repo; repo="$(mktmp_repo py-readonly)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_safe_diff "$mb"
  run_fix_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == *"--- a/src/x.py"* && "$STDOUT" == *"+++ b/src/x.py"* ]]; then
    note_pass
  else
    note_fail "py readonly: missing unified-diff headers. stdout: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "py readonly: expected exit 1, got $rc"; fi
}

# 1b. Bare-path diff input is normalised to a/ b/ prefix.
test_python_readonly_normalize() {
  local repo; repo="$(mktmp_repo py-normalize)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_bare_diff "$mb"
  run_fix_split "$repo" "$mb"
  local rc=$?
  # Mock emits "--- src/x.py" / "+++ src/x.py" — script must rewrite
  # to "--- a/src/x.py" / "+++ b/src/x.py".
  if [[ "$STDOUT" == *"--- a/src/x.py"* && "$STDOUT" == *"+++ b/src/x.py"* ]]; then
    note_pass
  else
    note_fail "py normalize: bare paths not rewritten to a/ b/. stdout: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "py normalize: expected exit 1, got $rc"; fi
}

# -- 2. Configured + safe-fixable + --apply -----------------------------

test_python_apply() {
  local repo; repo="$(mktmp_repo py-apply)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_safe_diff "$mb"
  run_fix_split "$repo" "$mb" --apply
  local rc=$?
  if [[ "$STDOUT" == "fixed src/x.py" ]]; then note_pass
  else note_fail "py apply: expected 'fixed src/x.py', got: $STDOUT"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "py apply: expected exit 0, got $rc"; fi
}

# -- 3. Configured + nothing fixable + read-only ------------------------

test_python_readonly_clean() {
  local repo; repo="$(mktmp_repo py-clean)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_clean "$mb"
  run_fix_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "py clean: expected empty stdout, got: $STDOUT"; fi
  if [[ "$STDERR" == *"python: no fixes available"* ]]; then note_pass
  else note_fail "py clean: missing 'no fixes available' stderr. stderr: $STDERR"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "py clean: expected exit 0, got $rc"; fi
}

# -- 4. Configured + unsafe-fixable + --apply-semantic ------------------

test_python_apply_semantic() {
  local repo; repo="$(mktmp_repo py-semantic)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_safe_diff "$mb"
  # Pre-snapshot of working tree so we can verify it's untouched after.
  mkdir -p "$repo/src"
  echo 'def existing(): pass' > "$repo/src/seed.py"
  local pre_hash; pre_hash="$(find "$repo" -type f -exec sha256sum {} + | LC_ALL=C sort | sha256sum)"

  run_fix_split "$repo" "$mb" --apply-semantic
  local rc=$?
  # The semantic mock emits the dead-code-removal diff (different from
  # the safe `import os, sys` split).
  if [[ "$STDOUT" == *"def dead"* && "$STDOUT" == *"--- a/src/x.py"* ]]; then note_pass
  else note_fail "py semantic: missing unsafe-mode diff. stdout: $STDOUT"; fi
  # Working tree clean afterward — semantic must not write.
  local post_hash; post_hash="$(find "$repo" -type f -exec sha256sum {} + | LC_ALL=C sort | sha256sum)"
  if [[ "$pre_hash" == "$post_hash" ]]; then note_pass
  else note_fail "py semantic: working tree changed after --apply-semantic"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "py semantic: expected exit 1, got $rc"; fi
}

# -- 5. --apply-semantic for standardrb -> empty-scope ------------------

test_standardrb_semantic_empty_scope() {
  local repo; repo="$(mktmp_repo rb-sr-semantic)"
  local mb; mb="$(mktmp_mockbin)"
  write_ruby_standardrb_config "$repo"
  mock_standardrb_anything "$mb"
  run_fix_split "$repo" "$mb" --apply-semantic
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "standardrb semantic: expected empty stdout, got: $STDOUT"; fi
  if [[ "$STDERR" == *"ruby: --apply-semantic empty-scope"* ]]; then note_pass
  else note_fail "standardrb semantic: missing empty-scope stderr. stderr: $STDERR"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "standardrb semantic: expected exit 0, got $rc"; fi
}

# -- 6. Mutually exclusive flags ----------------------------------------

test_mutex_flags() {
  local repo; repo="$(mktmp_repo mutex)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  PATH="$mb:$PATH" bash "$SCRIPT" --apply --apply-semantic "$repo" >/dev/null 2>"$TMPROOT/err.$$"
  local rc=$?
  local err; err="$(cat "$TMPROOT/err.$$")"; rm -f "$TMPROOT/err.$$"
  if [[ "$err" == *"mutually exclusive"* ]]; then note_pass
  else note_fail "mutex: missing 'mutually exclusive' message. stderr: $err"; fi
  if (( rc == 2 )); then note_pass
  else note_fail "mutex: expected exit 2, got $rc"; fi
}

# -- 7. Idempotency on --apply -----------------------------------------

# Mock that "fixes" something on first call, then returns clean on second.
# State carried through a marker file in the mockbin's parent dir so
# the mock survives across invocations.
mock_ruff_idempotent() {
  local mb="$1" marker="$mb/.ruff-applied"
  cat > "$mb/ruff" <<MOCK
#!/usr/bin/env bash
MARKER="$marker"
case "\$*" in
  *check*--fix*--diff*)
    if [[ -f "\$MARKER" ]]; then
      exit 0
    fi
    cat <<'DIFF'
--- a/src/x.py
+++ b/src/x.py
@@ -1,1 +1,1 @@
-x=1
+x = 1
DIFF
    exit 1 ;;
  *check*--fix*)
    touch "\$MARKER"
    exit 0 ;;
esac
MOCK
  chmod +x "$mb/ruff"
}

test_apply_idempotent() {
  local repo; repo="$(mktmp_repo idempotent)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_idempotent "$mb"

  # First call — should fix.
  run_fix_split "$repo" "$mb" --apply
  local rc1=$?
  if [[ "$STDOUT" == "fixed src/x.py" && $rc1 -eq 0 ]]; then note_pass
  else note_fail "idempotent first call: stdout='$STDOUT' rc=$rc1"; fi

  # Second call — nothing to fix, no `fixed` lines, exit 0.
  run_fix_split "$repo" "$mb" --apply
  local rc2=$?
  if [[ -z "$STDOUT" && $rc2 -eq 0 ]]; then note_pass
  else note_fail "idempotent second call: stdout='$STDOUT' rc=$rc2"; fi
  if [[ "$STDERR" == *"python: no fixes available"* ]]; then note_pass
  else note_fail "idempotent second call: missing 'no fixes available' stderr. stderr: $STDERR"; fi
}

# -- 8. Triple-run determinism on read-only and --apply-semantic --------

test_triple_run_readonly() {
  local repo; repo="$(mktmp_repo det-readonly)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_safe_diff "$mb"
  local r1 r2 r3
  r1="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  r2="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  r3="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  if [[ "$r1" == "$r2" && "$r2" == "$r3" ]]; then note_pass
  else note_fail "triple-run readonly: output diverged"; fi
}

test_triple_run_semantic() {
  local repo; repo="$(mktmp_repo det-semantic)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_safe_diff "$mb"
  local r1 r2 r3
  r1="$(PATH="$mb:$PATH" bash "$SCRIPT" --apply-semantic "$repo" 2>/dev/null)"
  r2="$(PATH="$mb:$PATH" bash "$SCRIPT" --apply-semantic "$repo" 2>/dev/null)"
  r3="$(PATH="$mb:$PATH" bash "$SCRIPT" --apply-semantic "$repo" 2>/dev/null)"
  if [[ "$r1" == "$r2" && "$r2" == "$r3" ]]; then note_pass
  else note_fail "triple-run semantic: output diverged"; fi
}

# -- 9. Polyglot — both sections appear ---------------------------------

test_polyglot_readonly_sections() {
  local repo; repo="$(mktmp_repo polyglot)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mkdir -p "$repo/src"
  printf 'var x = true;\n' > "$repo/src/render.js"
  mock_ruff_safe_diff "$mb"
  mock_biome_writes "$mb"
  run_fix_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == *"# python — 1 file with fixes available"* ]]; then note_pass
  else note_fail "polyglot: missing python section header. stdout: $STDOUT"; fi
  if [[ "$STDOUT" == *"# javascript — 1 file with fixes available"* ]]; then note_pass
  else note_fail "polyglot: missing javascript section header. stdout: $STDOUT"; fi
  if [[ "$STDOUT" == *"--- a/src/x.py"* && "$STDOUT" == *"--- a/src/render.js"* ]]; then note_pass
  else note_fail "polyglot: missing per-language diffs. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "polyglot: expected exit 1, got $rc"; fi
}

# -- 10. Copy-and-diff fallback — biome (no native diff mode) -----------

test_copy_and_diff_biome() {
  local repo; repo="$(mktmp_repo copy-diff)"
  local mb; mb="$(mktmp_mockbin)"
  write_javascript_config "$repo"
  mkdir -p "$repo/src"
  printf 'var x = true;\n' > "$repo/src/render.js"
  mock_biome_writes "$mb"

  local pre_content; pre_content="$(cat "$repo/src/render.js")"

  run_fix_split "$repo" "$mb"
  local rc=$?

  # The script must snapshot, run biome in the copy (mock writes to
  # the copy), then diff. Original must be untouched.
  local post_content; post_content="$(cat "$repo/src/render.js")"
  if [[ "$pre_content" == "$post_content" ]]; then note_pass
  else note_fail "copy-and-diff: original src/render.js was modified (working tree mutation)"; fi

  # Output must be a unified diff with a/ b/ headers.
  if [[ "$STDOUT" == *"--- a/src/render.js"* && "$STDOUT" == *"+++ b/src/render.js"* ]]; then
    note_pass
  else
    note_fail "copy-and-diff: missing a/ b/ headers. stdout: $STDOUT"
  fi
  # The diff should reflect the mock's edit (var → const safe_fix).
  if [[ "$STDOUT" == *"-var x = true;"* && "$STDOUT" == *"+const safe_fix = true;"* ]]; then
    note_pass
  else
    note_fail "copy-and-diff: diff content unexpected. stdout: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "copy-and-diff: expected exit 1, got $rc"; fi
}

# -- bonus coverage to keep parity with lint/format tests ---------------

test_not_configured() {
  local repo; repo="$(mktmp_repo unconfig)"
  local mb; mb="$(mktmp_mockbin)"
  echo '[project]' > "$repo/pyproject.toml"  # detected, NOT lintguini-managed
  mock_ruff_safe_diff "$mb"
  run_fix_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "not-configured: stdout should be empty, got: $STDOUT"; fi
  if [[ "$STDERR" == *"python: not configured (run /lintguini:configure --language python)"* ]]; then
    note_pass
  else
    note_fail "not-configured: missing greppable empty-scope stderr. stderr: $STDERR"
  fi
  if (( rc == 0 )); then note_pass
  else note_fail "not-configured: expected exit 0, got $rc"; fi
}

test_tool_missing() {
  local repo; repo="$(mktmp_repo no-tool)"
  local mb; mb="$(mktmp_mockbin)"  # empty
  write_python_config "$repo"
  PATH="$mb:/usr/bin:/bin" bash "$SCRIPT" "$repo" >/dev/null 2>"$TMPROOT/err.$$"
  local rc=$?
  local err; err="$(cat "$TMPROOT/err.$$")"; rm -f "$TMPROOT/err.$$"
  if [[ "$err" == *"python: ruff not on PATH (install ruff)"* ]]; then note_pass
  else note_fail "tool-missing: missing stderr hint. stderr: $err"; fi
  if (( rc == 3 )); then note_pass
  else note_fail "tool-missing: expected exit 3, got $rc"; fi
}

test_unknown_language_arg() {
  local repo; repo="$(mktmp_repo bad-lang)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  PATH="$mb:$PATH" bash "$SCRIPT" --language elixir "$repo" >/dev/null 2>&1
  local rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "unknown --language: expected rc=2 got $rc"; fi
}

# -- run -----------------------------------------------------------------

test_python_readonly_diff
test_python_readonly_normalize
test_python_apply
test_python_readonly_clean
test_python_apply_semantic
test_standardrb_semantic_empty_scope
test_mutex_flags
test_apply_idempotent
test_triple_run_readonly
test_triple_run_semantic
test_polyglot_readonly_sections
test_copy_and_diff_biome
test_not_configured
test_tool_missing
test_unknown_language_arg

if (( FAIL == 0 )); then
  echo "fix.test.sh: PASS — $PASS checks"
  exit 0
else
  echo "fix.test.sh: FAIL — $PASS passed, $FAIL failed" >&2
  for msg in "${FAILURES[@]}"; do
    echo "  - $msg" >&2
  done
  exit 1
fi
