#!/usr/bin/env bash
# format.test.sh — exercise bin/lintguini-format.sh end-to-end against
# mocked formatters on PATH. Two modes under test:
#   --check  -> diff-only, exit 1 when files would change, stdout
#               reports each file as `would format <path>`.
#   apply    -> rewrites files in place; stdout reports each modified
#               file as `formatted <path>`.
#
# Real formatters (ruff, biome, cargo, rubocop, standardrb, gofmt)
# aren't installed on the test box. Mocks emit the per-tool check
# output the per-tool parsers in lintguini-format.sh expect.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="$PLUGIN_ROOT/bin/lintguini-format.sh"

PASS=0
FAIL=0
FAILURES=()

note_pass() { PASS=$((PASS + 1)); }
note_fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
}

if [[ ! -x "$SCRIPT" ]]; then
  echo "FATAL: $SCRIPT not executable" >&2
  exit 2
fi

PROVENANCE='Generated by lintguini — see plugins/pronto/references/roll-your-own/lint-posture.md for the source of truth.'

TMPROOT="$(mktemp -d -t lintguini-format-tests.XXXXXX)"
trap 'rm -rf "$TMPROOT"' EXIT

mktmp_repo() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "$1.XXXXXX")"
  printf '%s' "$d"
}

mktmp_mockbin() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "mockbin.XXXXXX")"
  printf '%s' "$d"
}

# Provenance-marked config writers (mirror lint.test.sh).

write_python_config() {
  cat > "$1/pyproject.toml" <<EOF
# $PROVENANCE
[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "double"
EOF
}

write_javascript_config() {
  cat > "$1/biome.json" <<EOF
{
  "_provenance": "$PROVENANCE",
  "_band": "strict",
  "\$schema": "https://biomejs.dev/schemas/latest/schema.json",
  "linter": { "enabled": true },
  "formatter": { "enabled": true, "indentWidth": 2 }
}
EOF
  echo '{"name":"demo"}' > "$1/package.json"
}

write_rust_config() {
  cat > "$1/rustfmt.toml" <<EOF
# $PROVENANCE
edition = "2021"
EOF
  cat > "$1/Cargo.toml" <<'EOF'
[package]
name = "demo"
version = "0.1.0"
EOF
}

write_ruby_rubocop_config() {
  cat > "$1/.rubocop.yml" <<EOF
# $PROVENANCE
AllCops:
  NewCops: enable
EOF
  cat > "$1/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "rails"
EOF
}

write_ruby_standardrb_config() {
  cat > "$1/standard.yml" <<EOF
# $PROVENANCE
ruby_version: 3.3
EOF
  cat > "$1/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "standard"
EOF
}

write_go_config() {
  cat > "$1/.golangci.yml" <<EOF
# $PROVENANCE
linters:
  enable: [errcheck]
EOF
  cat > "$1/go.mod" <<'EOF'
module example.com/demo
go 1.22
EOF
}

# Mocks. Each tool needs to behave correctly for both check and apply
# invocations because the script calls check first then apply (in
# apply mode). The mocks branch on argv.

# mock_ruff_diffs <bindir> <file1> [<file2>...]
#   ruff format --check . -> "Would reformat: <f>" lines, exit 1
#   ruff format .         -> exit 0 (apply succeeded)
mock_ruff_diffs() {
  local mb="$1"; shift
  local files="$*"
  cat > "$mb/ruff" <<MOCK
#!/usr/bin/env bash
case "\$*" in
  *--check*)
$(for f in $files; do echo "    echo 'Would reformat: $f'"; done)
    exit 1
    ;;
  *format*)
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
MOCK
  chmod +x "$mb/ruff"
}

mock_ruff_clean() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
  chmod +x "$1/ruff"
}

# mock_ruff_apply_failure — check shows diffs, apply exits non-zero
mock_ruff_apply_failure() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
case "$*" in
  *--check*)
    echo "Would reformat: src/x.py"
    exit 1 ;;
  *format*)
    echo "panic: filesystem error" >&2
    exit 2 ;;
esac
MOCK
  chmod +x "$1/ruff"
}

mock_biome_diffs() {
  local mb="$1"; shift
  local files="$*"
  cat > "$mb/biome" <<MOCK
#!/usr/bin/env bash
case "\$*" in
  *check*--formatter-enabled*|*check*--linter-enabled*)
$(for f in $files; do echo "    echo '::error title=format,file=$f,line=1,col=1::file would be reformatted'"; done)
    exit 1
    ;;
  *format*--write*)
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
MOCK
  chmod +x "$mb/biome"
}

mock_cargo_diffs() {
  local mb="$1"; shift
  local files="$*"
  cat > "$mb/cargo" <<MOCK
#!/usr/bin/env bash
case "\$*" in
  *fmt*--check*)
$(for f in $files; do echo "    echo 'Diff in $f at line 12:'"; done)
    exit 1
    ;;
  *fmt*)
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
MOCK
  chmod +x "$mb/cargo"
}

mock_rubocop_diffs() {
  cat > "$1/rubocop" <<'MOCK'
#!/usr/bin/env bash
case "$*" in
  *--format*json*)
    cat <<JSON
{"files":[{"path":"lib/widget.rb","offenses":[{"cop_name":"Layout/IndentationWidth","message":"x","location":{"start_line":1,"line":1}}]}],"summary":{"offense_count":1}}
JSON
    exit 1 ;;
  *-A*)
    exit 0 ;;
esac
MOCK
  chmod +x "$1/rubocop"
}

mock_standardrb_diffs() {
  cat > "$1/standardrb" <<'MOCK'
#!/usr/bin/env bash
case "$*" in
  *--format*json*)
    cat <<JSON
{"files":[{"path":"lib/x.rb","offenses":[{"cop_name":"Standard/SemanticBlocks","message":"x","location":{"start_line":1,"line":1}}]}],"summary":{"offense_count":1}}
JSON
    exit 1 ;;
  *--fix*)
    exit 0 ;;
esac
MOCK
  chmod +x "$1/standardrb"
}

mock_gofmt_diffs() {
  local mb="$1"; shift
  local files="$*"
  cat > "$mb/gofmt" <<MOCK
#!/usr/bin/env bash
case "\$*" in
  *-l*)
$(for f in $files; do echo "    echo '$f'"; done)
    exit 0
    ;;
  *-w*)
    exit 0 ;;
esac
MOCK
  chmod +x "$mb/gofmt"
}

run_format_split() {
  local repo="$1" mockbin="$2"; shift 2
  local out_f="$TMPROOT/out.$$" err_f="$TMPROOT/err.$$"
  PATH="$mockbin:$PATH" bash "$SCRIPT" "$@" "$repo" >"$out_f" 2>"$err_f"
  local rc=$?
  STDOUT="$(cat "$out_f")"
  STDERR="$(cat "$err_f")"
  rm -f "$out_f" "$err_f"
  return $rc
}

# -- 1. --check on tree with diffs -> `would format X`, exit 1 ---------

test_python_check_diffs() {
  local repo; repo="$(mktmp_repo py-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_diffs "$mb" src/auth.py src/api.py
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format src/api.py"* \
      && "$STDOUT" == *"would format src/auth.py"* ]]; then note_pass
  else note_fail "py --check: missing would-format lines. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "py --check: expected exit 1, got $rc"; fi
}

test_javascript_check_diffs() {
  local repo; repo="$(mktmp_repo js-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_javascript_config "$repo"
  mock_biome_diffs "$mb" src/render.js
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format src/render.js"* ]]; then note_pass
  else note_fail "js --check: missing would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "js --check: expected exit 1, got $rc"; fi
}

test_rust_check_diffs() {
  local repo; repo="$(mktmp_repo rust-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_rust_config "$repo"
  mock_cargo_diffs "$mb" src/main.rs
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format src/main.rs"* ]]; then note_pass
  else note_fail "rust --check: missing would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "rust --check: expected exit 1, got $rc"; fi
}

test_ruby_rubocop_check_diffs() {
  local repo; repo="$(mktmp_repo rb-rubocop-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_ruby_rubocop_config "$repo"
  mock_rubocop_diffs "$mb"
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format lib/widget.rb"* ]]; then note_pass
  else note_fail "ruby rubocop --check: missing would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "ruby rubocop --check: expected exit 1, got $rc"; fi
}

test_ruby_standardrb_check_diffs() {
  local repo; repo="$(mktmp_repo rb-standardrb-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_ruby_standardrb_config "$repo"
  mock_standardrb_diffs "$mb"
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format lib/x.rb"* ]]; then note_pass
  else note_fail "ruby standardrb --check: missing would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "ruby standardrb --check: expected exit 1, got $rc"; fi
}

test_go_check_diffs() {
  local repo; repo="$(mktmp_repo go-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_go_config "$repo"
  mock_gofmt_diffs "$mb" main.go
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"would format main.go"* ]]; then note_pass
  else note_fail "go --check: missing would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "go --check: expected exit 1, got $rc"; fi
}

# -- 2. --check on clean tree -> empty stdout, exit 0 -------------------

test_python_check_clean() {
  local repo; repo="$(mktmp_repo py-check-clean)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_clean "$mb"
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ -z "$STDOUT" && $rc -eq 0 ]]; then note_pass
  else note_fail "py --check clean: stdout='$STDOUT' rc=$rc"; fi
}

# -- 3. Apply mode -> `formatted X`, exit 0 -----------------------------

test_python_apply() {
  local repo; repo="$(mktmp_repo py-apply)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_diffs "$mb" src/auth.py src/api.py
  run_format_split "$repo" "$mb"
  local rc=$?
  local expected=$'formatted src/api.py\nformatted src/auth.py'
  if [[ "$STDOUT" == "$expected" ]]; then note_pass
  else note_fail "py apply: expected sorted formatted lines. got: $STDOUT"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "py apply: expected exit 0, got $rc"; fi
}

test_javascript_apply() {
  local repo; repo="$(mktmp_repo js-apply)"
  local mb; mb="$(mktmp_mockbin)"
  write_javascript_config "$repo"
  mock_biome_diffs "$mb" src/render.js
  run_format_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == "formatted src/render.js" ]]; then note_pass
  else note_fail "js apply: got: $STDOUT"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "js apply: expected exit 0, got $rc"; fi
}

# Apply on clean tree -> no `formatted` lines, exit 0.
test_apply_clean_no_lines() {
  local repo; repo="$(mktmp_repo apply-clean)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_clean "$mb"
  run_format_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" && $rc -eq 0 ]]; then note_pass
  else note_fail "apply clean: stdout='$STDOUT' rc=$rc"; fi
}

# -- 4. Not configured -> empty-scope on stderr, exit 0 ----------------

test_not_configured() {
  local repo; repo="$(mktmp_repo unconfig)"
  local mb; mb="$(mktmp_mockbin)"
  echo '[project]' > "$repo/pyproject.toml"  # detected, NOT configured
  mock_ruff_diffs "$mb" src/x.py
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "not-configured: stdout should be empty, got: $STDOUT"; fi
  if [[ "$STDERR" == *"python: not configured (run /lintguini:configure --language python)"* ]]; then
    note_pass
  else
    note_fail "not-configured: missing greppable empty-scope message. stderr: $STDERR"
  fi
  if (( rc == 0 )); then note_pass
  else note_fail "not-configured: expected exit 0, got $rc"; fi
}

# -- 5. Tool not on PATH -> stderr message, exit 3 ---------------------

test_tool_missing() {
  local repo; repo="$(mktmp_repo no-tool)"
  local mb; mb="$(mktmp_mockbin)"  # empty
  write_python_config "$repo"
  local out_f="$TMPROOT/out.$$" err_f="$TMPROOT/err.$$"
  PATH="$mb:/usr/bin:/bin" bash "$SCRIPT" --check "$repo" >"$out_f" 2>"$err_f"
  local rc=$?
  STDOUT="$(cat "$out_f")"; STDERR="$(cat "$err_f")"
  rm -f "$out_f" "$err_f"
  if [[ "$STDERR" == *"python: ruff not on PATH (install ruff)"* ]]; then note_pass
  else note_fail "tool-missing: missing stderr hint. stderr: $STDERR"; fi
  if (( rc == 3 )); then note_pass
  else note_fail "tool-missing: expected exit 3, got $rc"; fi
}

# -- 6. Polyglot -> sectioned output ------------------------------------

test_polyglot_check_sections() {
  local repo; repo="$(mktmp_repo polyglot-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mock_ruff_diffs "$mb" src/x.py
  mock_biome_diffs "$mb" src/y.js
  run_format_split "$repo" "$mb" --check
  local rc=$?
  if [[ "$STDOUT" == *"# python — 1 file would be reformatted"* \
      && "$STDOUT" == *"# javascript — 1 file would be reformatted"* ]]; then note_pass
  else note_fail "polyglot --check: missing section headers. stdout: $STDOUT"; fi
  if [[ "$STDOUT" == *"would format src/x.py"* \
      && "$STDOUT" == *"would format src/y.js"* ]]; then note_pass
  else note_fail "polyglot --check: missing per-language would-format. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "polyglot --check: expected exit 1, got $rc"; fi
}

test_polyglot_apply_sections() {
  local repo; repo="$(mktmp_repo polyglot-apply)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mock_ruff_diffs "$mb" src/x.py src/y.py
  mock_biome_diffs "$mb" src/z.js
  run_format_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == *"# python — 2 files formatted"* \
      && "$STDOUT" == *"# javascript — 1 file formatted"* ]]; then note_pass
  else note_fail "polyglot apply: missing section headers. stdout: $STDOUT"; fi
  if [[ "$STDOUT" == *"formatted src/x.py"* \
      && "$STDOUT" == *"formatted src/z.js"* ]]; then note_pass
  else note_fail "polyglot apply: missing per-language formatted. stdout: $STDOUT"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "polyglot apply: expected exit 0, got $rc"; fi
}

# -- 7. --language scopes to one language; no header -------------------

test_language_scope() {
  local repo; repo="$(mktmp_repo polyglot-scoped)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mock_ruff_diffs "$mb" src/x.py
  mock_biome_diffs "$mb" src/y.js
  run_format_split "$repo" "$mb" --check --language python
  local rc=$?
  if [[ "$STDOUT" != *"src/y.js"* && "$STDOUT" == *"would format src/x.py"* ]]; then note_pass
  else note_fail "scope: js leaked or python missing. stdout: $STDOUT"; fi
  if [[ "$STDOUT" != *"# python"* ]]; then note_pass
  else note_fail "scope: header should not appear with --language. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "scope: expected exit 1, got $rc"; fi
}

# -- 8. Triple-run determinism ------------------------------------------

test_triple_run_determinism_check() {
  local repo; repo="$(mktmp_repo determinism-check)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_diffs "$mb" src/a.py src/b.py src/c.py
  local r1 r2 r3
  r1="$(PATH="$mb:$PATH" bash "$SCRIPT" --check "$repo" 2>/dev/null)"
  r2="$(PATH="$mb:$PATH" bash "$SCRIPT" --check "$repo" 2>/dev/null)"
  r3="$(PATH="$mb:$PATH" bash "$SCRIPT" --check "$repo" 2>/dev/null)"
  if [[ "$r1" == "$r2" && "$r2" == "$r3" ]]; then note_pass
  else note_fail "triple-run --check: output diverged"; fi
}

# -- 9. Apply failure -> exit 4 -----------------------------------------

test_apply_failure() {
  local repo; repo="$(mktmp_repo apply-fail)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_apply_failure "$mb"
  PATH="$mb:$PATH" bash "$SCRIPT" "$repo" >/dev/null 2>&1
  local rc=$?
  if (( rc == 4 )); then note_pass
  else note_fail "apply failure: expected exit 4, got $rc"; fi
}

# -- 10. Argument errors ------------------------------------------------

test_argument_errors() {
  local repo; repo="$(mktmp_repo args)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"

  PATH="$mb:$PATH" bash "$SCRIPT" --language ruby "$repo" >/dev/null 2>&1
  local rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "--language not detected: expected rc=2 got $rc"; fi

  PATH="$mb:$PATH" bash "$SCRIPT" --language elixir "$repo" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "unknown --language: expected rc=2 got $rc"; fi
}

# -- run -----------------------------------------------------------------

test_python_check_diffs
test_javascript_check_diffs
test_rust_check_diffs
test_ruby_rubocop_check_diffs
test_ruby_standardrb_check_diffs
test_go_check_diffs
test_python_check_clean
test_python_apply
test_javascript_apply
test_apply_clean_no_lines
test_not_configured
test_tool_missing
test_polyglot_check_sections
test_polyglot_apply_sections
test_language_scope
test_triple_run_determinism_check
test_apply_failure
test_argument_errors

if (( FAIL == 0 )); then
  echo "format.test.sh: PASS — $PASS checks"
  exit 0
else
  echo "format.test.sh: FAIL — $PASS passed, $FAIL failed" >&2
  for msg in "${FAILURES[@]}"; do
    echo "  - $msg" >&2
  done
  exit 1
fi
