#!/usr/bin/env bash
# lint.test.sh — exercise bin/lintguini-lint.sh end-to-end against
# mocked linters on PATH. The contract under test is the projection
# from each tool's native JSON / GitHub-format output to the locked
# `<path>:<line>:<rule>:<message>` finding shape M5's
# score-lint-pass-rate.sh will parse.
#
# Real linters (ruff, biome, cargo, rubocop, standardrb, golangci-lint)
# aren't installed on the test box. Each test stages a tempdir on
# PATH containing a fake binary that emits known output, then
# verifies the script's projection. This is the same shape inkwell's
# tests use for tool-dispatch coverage.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPT="$PLUGIN_ROOT/bin/lintguini-lint.sh"

PASS=0
FAIL=0
FAILURES=()

note_pass() { PASS=$((PASS + 1)); }
note_fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
}

if [[ ! -x "$SCRIPT" ]]; then
  echo "FATAL: $SCRIPT not executable" >&2
  exit 2
fi

PROVENANCE='Generated by lintguini — see plugins/pronto/references/roll-your-own/lint-posture.md for the source of truth.'

TMPROOT="$(mktemp -d -t lintguini-lint-tests.XXXXXX)"
trap 'rm -rf "$TMPROOT"' EXIT

mktmp_repo() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "$1.XXXXXX")"
  printf '%s' "$d"
}

mktmp_mockbin() {
  local d
  d="$(mktemp -d -p "$TMPROOT" "mockbin.XXXXXX")"
  printf '%s' "$d"
}

# write_python_config <repo>
#   Plant a provenance-marked pyproject.toml so is_configured(python) -> true.
write_python_config() {
  cat > "$1/pyproject.toml" <<EOF
# $PROVENANCE
# Strict band — full rubric baseline.

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
EOF
}

write_javascript_config() {
  cat > "$1/biome.json" <<EOF
{
  "_provenance": "$PROVENANCE",
  "_band": "strict",
  "\$schema": "https://biomejs.dev/schemas/latest/schema.json",
  "linter": { "enabled": true, "rules": { "recommended": true } },
  "formatter": { "enabled": true, "indentWidth": 2 }
}
EOF
  echo '{"name":"demo"}' > "$1/package.json"
}

write_typescript_config() {
  write_javascript_config "$1"
  cat > "$1/tsconfig.json" <<EOF
{
  "_provenance": "$PROVENANCE",
  "_band": "strict",
  "compilerOptions": { "strict": true }
}
EOF
}

write_rust_config() {
  cat > "$1/rustfmt.toml" <<EOF
# $PROVENANCE
edition = "2021"
EOF
  cat > "$1/Cargo.toml" <<'EOF'
[package]
name = "demo"
version = "0.1.0"
EOF
}

write_ruby_rubocop_config() {
  cat > "$1/.rubocop.yml" <<EOF
# $PROVENANCE
AllCops:
  NewCops: enable
EOF
  cat > "$1/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "rails"
EOF
}

write_ruby_standardrb_config() {
  cat > "$1/standard.yml" <<EOF
# $PROVENANCE
ruby_version: 3.3
EOF
  cat > "$1/Gemfile" <<'EOF'
source "https://rubygems.org"
gem "standard"
EOF
}

write_go_config() {
  cat > "$1/.golangci.yml" <<EOF
# $PROVENANCE
linters:
  enable: [errcheck]
EOF
  cat > "$1/go.mod" <<'EOF'
module example.com/demo
go 1.22
EOF
}

# Mock factories. Each writes a fake binary at <bindir>/<tool> that
# emits known output and exits with the right code.

mock_ruff_violations() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
[
  {"filename": "src/auth.py", "code": "F401", "message": "imported but unused: typing.Optional", "location": {"row": 67, "column": 1}},
  {"filename": "src/auth.py", "code": "E501", "message": "line too long (120 > 88 characters)", "location": {"row": 42, "column": 89}},
  {"filename": "src/api.py",  "code": "E711", "message": "comparison to None should be 'is None'", "location": {"row": 12, "column": 3}}
]
JSON
exit 1
MOCK
  chmod +x "$1/ruff"
}

mock_ruff_clean() {
  cat > "$1/ruff" <<'MOCK'
#!/usr/bin/env bash
echo "[]"
exit 0
MOCK
  chmod +x "$1/ruff"
}

mock_biome_violations() {
  cat > "$1/biome" <<'MOCK'
#!/usr/bin/env bash
cat <<'OUT'
::error title=lint/correctness/noUnusedVariables,file=src/render.js,line=88,col=5,endLine=88,endCol=14::Unexpected unused variable foo
OUT
exit 1
MOCK
  chmod +x "$1/biome"
}

mock_biome_clean() {
  cat > "$1/biome" <<'MOCK'
#!/usr/bin/env bash
exit 0
MOCK
  chmod +x "$1/biome"
}

mock_cargo_violations() {
  cat > "$1/cargo" <<'MOCK'
#!/usr/bin/env bash
cat <<'NDJSON'
{"reason":"compiler-message","message":{"code":{"code":"clippy::needless_return"},"level":"warning","message":"unneeded `return` statement","spans":[{"file_name":"src/main.rs","line_start":12,"column_start":5,"is_primary":true}]}}
{"reason":"build-script-executed","linked_libs":[]}
{"reason":"compiler-message","message":{"code":{"code":"clippy::redundant_clone"},"level":"warning","message":"redundant clone","spans":[{"file_name":"src/lib.rs","line_start":7,"column_start":1,"is_primary":true}]}}
NDJSON
exit 101
MOCK
  chmod +x "$1/cargo"
}

mock_rubocop_violations() {
  cat > "$1/rubocop" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
{
  "files": [
    {
      "path": "lib/widget.rb",
      "offenses": [
        {"cop_name": "Style/FrozenStringLiteralComment", "message": "Missing magic comment", "location": {"start_line": 1, "start_column": 1, "line": 1, "column": 1, "length": 1}},
        {"cop_name": "Layout/LineLength", "message": "Line is too long. [125/120]", "location": {"start_line": 42, "start_column": 121, "line": 42, "column": 121, "length": 5}}
      ]
    }
  ],
  "summary": {"offense_count": 2, "target_file_count": 1, "inspected_file_count": 1}
}
JSON
exit 1
MOCK
  chmod +x "$1/rubocop"
}

mock_standardrb_violations() {
  cat > "$1/standardrb" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
{"files": [{"path": "lib/x.rb", "offenses": [{"cop_name": "Standard/SemanticBlocks", "message": "Use {} for non-control flow blocks.", "location": {"start_line": 5, "line": 5}}]}]}
JSON
exit 1
MOCK
  chmod +x "$1/standardrb"
}

mock_golangci_violations() {
  cat > "$1/golangci-lint" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
{
  "Issues": [
    {"FromLinter": "errcheck", "Text": "Error return value of \"x.Close\" is not checked", "Pos": {"Filename": "main.go", "Line": 22, "Column": 8}},
    {"FromLinter": "ineffassign", "Text": "ineffectual assignment to err", "Pos": {"Filename": "main.go", "Line": 11, "Column": 5}}
  ]
}
JSON
exit 1
MOCK
  chmod +x "$1/golangci-lint"
}

# run_lint <repo> <mockbin> [extra script flags...]
run_lint() {
  local repo="$1" mockbin="$2"; shift 2
  PATH="$mockbin:$PATH" bash "$SCRIPT" "$@" "$repo" 2>&1
}

run_lint_split() {
  # Run script, capture stdout and stderr separately. Output:
  #   stdout=...
  #   stderr=...
  # via tempfiles.
  local repo="$1" mockbin="$2"; shift 2
  local out_f="$TMPROOT/out.$$" err_f="$TMPROOT/err.$$"
  PATH="$mockbin:$PATH" bash "$SCRIPT" "$@" "$repo" >"$out_f" 2>"$err_f"
  local rc=$?
  STDOUT="$(cat "$out_f")"
  STDERR="$(cat "$err_f")"
  rm -f "$out_f" "$err_f"
  return $rc
}

# -- 1. Per-language: configured + violations -> projected findings ------

test_python_violations() {
  local repo; repo="$(mktmp_repo py-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  local expected
  expected=$'src/api.py:12:E711:comparison to None should be \'is None\'\nsrc/auth.py:42:E501:line too long (120 > 88 characters)\nsrc/auth.py:67:F401:imported but unused: typing.Optional'
  if [[ "$STDOUT" == "$expected" ]]; then note_pass
  else note_fail "python projection mismatch. got: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "python violations: expected exit 1, got $rc"; fi
}

test_javascript_violations() {
  local repo; repo="$(mktmp_repo js-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_javascript_config "$repo"
  mock_biome_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == "src/render.js:88:lint/correctness/noUnusedVariables:Unexpected unused variable foo" ]]; then
    note_pass
  else
    note_fail "javascript projection mismatch. got: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "javascript violations: expected exit 1, got $rc"; fi
}

test_typescript_violations() {
  local repo; repo="$(mktmp_repo ts-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_typescript_config "$repo"
  mock_biome_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == "src/render.js:88:lint/correctness/noUnusedVariables:Unexpected unused variable foo" ]]; then
    note_pass
  else
    note_fail "typescript projection mismatch. got: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "typescript violations: expected exit 1, got $rc"; fi
}

test_rust_violations() {
  local repo; repo="$(mktmp_repo rust-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_rust_config "$repo"
  mock_cargo_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  local expected
  expected=$'src/lib.rs:7:clippy::redundant_clone:redundant clone\nsrc/main.rs:12:clippy::needless_return:unneeded `return` statement'
  if [[ "$STDOUT" == "$expected" ]]; then note_pass
  else note_fail "rust projection mismatch. got: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "rust violations: expected exit 1, got $rc"; fi
}

test_ruby_rubocop_violations() {
  local repo; repo="$(mktmp_repo rb-rubocop-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_ruby_rubocop_config "$repo"
  mock_rubocop_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  local expected
  expected=$'lib/widget.rb:1:Style/FrozenStringLiteralComment:Missing magic comment\nlib/widget.rb:42:Layout/LineLength:Line is too long. [125/120]'
  if [[ "$STDOUT" == "$expected" ]]; then note_pass
  else note_fail "ruby rubocop projection mismatch. got: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "ruby rubocop violations: expected exit 1, got $rc"; fi
}

test_ruby_standardrb_violations() {
  local repo; repo="$(mktmp_repo rb-standardrb-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_ruby_standardrb_config "$repo"
  mock_standardrb_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == "lib/x.rb:5:Standard/SemanticBlocks:Use {} for non-control flow blocks." ]]; then
    note_pass
  else
    note_fail "ruby standardrb projection mismatch. got: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "ruby standardrb violations: expected exit 1, got $rc"; fi
}

test_go_violations() {
  local repo; repo="$(mktmp_repo go-violations)"
  local mb; mb="$(mktmp_mockbin)"
  write_go_config "$repo"
  mock_golangci_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  local expected
  expected=$'main.go:11:ineffassign:ineffectual assignment to err\nmain.go:22:errcheck:Error return value of "x.Close" is not checked'
  if [[ "$STDOUT" == "$expected" ]]; then note_pass
  else note_fail "go projection mismatch. got: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "go violations: expected exit 1, got $rc"; fi
}

# -- 2. Configured + clean -> no findings, exit 0 -----------------------

test_python_clean() {
  local repo; repo="$(mktmp_repo py-clean)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_clean "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "python clean: expected empty stdout, got: $STDOUT"; fi
  if (( rc == 0 )); then note_pass
  else note_fail "python clean: expected exit 0, got $rc"; fi
}

test_javascript_clean() {
  local repo; repo="$(mktmp_repo js-clean)"
  local mb; mb="$(mktmp_mockbin)"
  write_javascript_config "$repo"
  mock_biome_clean "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" && $rc -eq 0 ]]; then note_pass
  else note_fail "javascript clean: stdout='$STDOUT' rc=$rc"; fi
}

# -- 3. Not configured -> empty-scope on stderr, exit 0 -----------------

test_not_configured_python() {
  local repo; repo="$(mktmp_repo py-unconfig)"
  local mb; mb="$(mktmp_mockbin)"
  # python is detected via pyproject.toml but NOT lintguini-managed
  echo '[project]' > "$repo/pyproject.toml"
  mock_ruff_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ -z "$STDOUT" ]]; then note_pass
  else note_fail "not-configured: stdout should be empty, got: $STDOUT"; fi
  if [[ "$STDERR" == *"python: not configured (run /lintguini:configure --language python)"* ]]; then
    note_pass
  else
    note_fail "not-configured: missing greppable empty-scope message. stderr: $STDERR"
  fi
  if (( rc == 0 )); then note_pass
  else note_fail "not-configured: expected exit 0, got $rc"; fi
}

# -- 4. Tool not on PATH -> stderr message, exit 3 ----------------------

test_tool_missing_python() {
  local repo; repo="$(mktmp_repo py-no-tool)"
  local mb; mb="$(mktmp_mockbin)"  # empty — no ruff in here
  write_python_config "$repo"
  # Use a sanitized PATH that excludes whatever real ruff might be installed.
  local out_f="$TMPROOT/out.$$" err_f="$TMPROOT/err.$$"
  PATH="$mb:/usr/bin:/bin" bash "$SCRIPT" "$repo" >"$out_f" 2>"$err_f"
  local rc=$?
  STDOUT="$(cat "$out_f")"; STDERR="$(cat "$err_f")"
  rm -f "$out_f" "$err_f"
  if [[ "$STDERR" == *"python: ruff not on PATH (install ruff)"* ]]; then note_pass
  else note_fail "tool-missing: missing stderr hint. stderr: $STDERR"; fi
  if (( rc == 3 )); then note_pass
  else note_fail "tool-missing: expected exit 3, got $rc"; fi
}

# -- 5. Polyglot — multiple configured langs, sectioned output ----------

test_polyglot_sections() {
  local repo; repo="$(mktmp_repo polyglot)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mock_ruff_violations "$mb"
  mock_biome_violations "$mb"
  run_lint_split "$repo" "$mb"
  local rc=$?
  if [[ "$STDOUT" == *"# python — 3 findings"* \
      && "$STDOUT" == *"# javascript — 1 finding"* ]]; then
    note_pass
  else
    note_fail "polyglot: missing section headers. stdout: $STDOUT"
  fi
  # Findings appear after their respective headers.
  if [[ "$STDOUT" == *"src/auth.py:42:E501"* \
      && "$STDOUT" == *"src/render.js:88:lint/correctness/noUnusedVariables"* ]]; then
    note_pass
  else
    note_fail "polyglot: missing per-language findings. stdout: $STDOUT"
  fi
  if (( rc == 1 )); then note_pass
  else note_fail "polyglot: expected exit 1, got $rc"; fi
}

# -- 6. --language scopes to one language; no header --------------------

test_language_scope() {
  local repo; repo="$(mktmp_repo polyglot-scoped)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  mock_ruff_violations "$mb"
  mock_biome_violations "$mb"
  run_lint_split "$repo" "$mb" --language python
  local rc=$?
  if [[ "$STDOUT" != *"#"*"javascript"* && "$STDOUT" == *"src/auth.py:42:E501"* ]]; then
    note_pass
  else
    note_fail "scope: javascript leaked or python missing. stdout: $STDOUT"
  fi
  # Single-language scope -> no header.
  if [[ "$STDOUT" != *"# python"* ]]; then note_pass
  else note_fail "scope: header should not appear with --language. stdout: $STDOUT"; fi
  if (( rc == 1 )); then note_pass
  else note_fail "scope: expected exit 1, got $rc"; fi
}

# -- 7. Triple-run determinism ------------------------------------------

test_triple_run_determinism() {
  local repo; repo="$(mktmp_repo determinism)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  mock_ruff_violations "$mb"
  local r1 r2 r3
  r1="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  r2="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  r3="$(PATH="$mb:$PATH" bash "$SCRIPT" "$repo" 2>/dev/null)"
  if [[ "$r1" == "$r2" && "$r2" == "$r3" ]]; then note_pass
  else note_fail "triple-run output diverged"; fi
}

# -- 8. --language argument errors --------------------------------------

test_argument_errors() {
  local repo; repo="$(mktmp_repo args)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"  # python detected + configured

  PATH="$mb:$PATH" bash "$SCRIPT" --language ruby "$repo" >/dev/null 2>&1
  local rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "--language not detected: expected rc=2 got $rc"; fi

  PATH="$mb:$PATH" bash "$SCRIPT" --language elixir "$repo" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "unknown --language: expected rc=2 got $rc"; fi

  PATH="$mb:$PATH" bash "$SCRIPT" "$repo/does-not-exist" >/dev/null 2>&1
  rc=$?
  if (( rc == 2 )); then note_pass
  else note_fail "non-existent REPO_ROOT: expected rc=2 got $rc"; fi
}

# -- 9. Section header singular/plural ----------------------------------

test_section_header_singular() {
  local repo; repo="$(mktmp_repo singular)"
  local mb; mb="$(mktmp_mockbin)"
  write_python_config "$repo"
  write_javascript_config "$repo"
  # Mock ruff with exactly 1 finding.
  cat > "$mb/ruff" <<'MOCK'
#!/usr/bin/env bash
cat <<'JSON'
[{"filename":"src/x.py","code":"F401","message":"unused","location":{"row":1,"column":1}}]
JSON
exit 1
MOCK
  chmod +x "$mb/ruff"
  mock_biome_violations "$mb"  # 1 finding
  run_lint_split "$repo" "$mb"
  if [[ "$STDOUT" == *"# python — 1 finding"* \
      && "$STDOUT" == *"# javascript — 1 finding"* ]]; then note_pass
  else note_fail "section header singular form missing. stdout: $STDOUT"; fi
}

# -- run -----------------------------------------------------------------

test_python_violations
test_javascript_violations
test_typescript_violations
test_rust_violations
test_ruby_rubocop_violations
test_ruby_standardrb_violations
test_go_violations
test_python_clean
test_javascript_clean
test_not_configured_python
test_tool_missing_python
test_polyglot_sections
test_language_scope
test_triple_run_determinism
test_argument_errors
test_section_header_singular

if (( FAIL == 0 )); then
  echo "lint.test.sh: PASS — $PASS checks"
  exit 0
else
  echo "lint.test.sh: FAIL — $PASS passed, $FAIL failed" >&2
  for msg in "${FAILURES[@]}"; do
    echo "  - $msg" >&2
  done
  exit 1
fi
