#!/usr/bin/env bash
# templates.test.sh — verify every per-language template file under
# plugins/lintguini/templates/ satisfies ADR-008's invariants:
#
#   1. Provenance. The first non-blank line is the lintguini-generated
#      comment naming the rubric reference. JSON has no comment syntax,
#      so the equivalent assertion is that "_provenance" is the first
#      key (the convention pinned by the brief).
#   2. Parses-as-format. TOML files parse via python3 tomllib, JSON via
#      jq, YAML via the available YAML parser (yq / ruby / python yaml).
#      A config that doesn't parse is not a config.
#
# Coverage matches the rubric's six languages plus Ruby's dual-path
# (rubocop and standardrb subdirectories).

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$HERE/../.." && pwd)"
TEMPLATES="$PLUGIN_ROOT/templates"

PASS=0
FAIL=0
FAILURES=()

note_pass() { PASS=$((PASS + 1)); }
note_fail() {
  FAIL=$((FAIL + 1))
  FAILURES+=("$1")
}

if [[ ! -d "$TEMPLATES" ]]; then
  echo "FATAL: templates dir missing at $TEMPLATES" >&2
  exit 2
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "FATAL: jq required" >&2
  exit 2
fi

# Pick a YAML parser that's actually present on this host. Python yq
# (the Andrey Kislyuk fork) reads from stdin; standard yq from
# Mike Farah takes a filter argument. ruby's yaml stdlib is the
# cleanest fallback.
yaml_check() {
  local f="$1"
  if command -v ruby >/dev/null 2>&1; then
    ruby -ryaml -e 'YAML.load_file(ARGV[0])' "$f" >/dev/null 2>&1
  elif command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' 2>/dev/null; then
    python3 -c "import yaml,sys; yaml.safe_load(open(sys.argv[1]))" "$f" >/dev/null 2>&1
  elif command -v yq >/dev/null 2>&1; then
    # Try Mike Farah's interface first, fall back to python yq's stdin form.
    yq eval . "$f" >/dev/null 2>&1 || yq <"$f" >/dev/null 2>&1
  else
    echo "FATAL: no YAML parser available (tried ruby, python yaml, yq)" >&2
    exit 2
  fi
}

# The exact provenance string ADR-008 §4 pins.
PROVENANCE_TEXT='Generated by lintguini — see plugins/pronto/references/roll-your-own/lint-posture.md for the source of truth.'

check_provenance_comment() {
  local f="$1"
  # First non-blank line, with leading whitespace trimmed.
  local first
  first=$(awk 'NF { sub(/^[[:space:]]+/, ""); print; exit }' "$f")
  case "$first" in
    "# $PROVENANCE_TEXT") return 0 ;;
    "// $PROVENANCE_TEXT") return 0 ;;
    *) return 1 ;;
  esac
}

check_provenance_json() {
  local f="$1"
  local first_key
  first_key=$(jq -r 'keys_unsorted[0] // ""' "$f" 2>/dev/null)
  if [[ "$first_key" != "_provenance" ]]; then
    return 1
  fi
  local val
  val=$(jq -r '._provenance // ""' "$f" 2>/dev/null)
  [[ "$val" == "$PROVENANCE_TEXT" ]]
}

check_parses_toml() {
  python3 -c "import tomllib,sys; tomllib.loads(open(sys.argv[1],'rb').read().decode())" "$1" >/dev/null 2>&1
}

check_parses_json() {
  jq empty "$1" >/dev/null 2>&1
}

# Walk every template file. Dispatch by extension.
while IFS= read -r f; do
  rel="${f#$TEMPLATES/}"
  case "$f" in
    *.toml)
      if check_provenance_comment "$f"; then note_pass; else note_fail "$rel: missing/wrong provenance comment"; fi
      if check_parses_toml "$f"; then note_pass; else note_fail "$rel: TOML parse failed"; fi
      ;;
    *.json)
      if check_provenance_json "$f"; then note_pass; else note_fail "$rel: missing/wrong _provenance JSON key"; fi
      if check_parses_json "$f"; then note_pass; else note_fail "$rel: JSON parse failed"; fi
      ;;
    *.yml|*.yaml)
      if check_provenance_comment "$f"; then note_pass; else note_fail "$rel: missing/wrong provenance comment"; fi
      if yaml_check "$f"; then note_pass; else note_fail "$rel: YAML parse failed"; fi
      ;;
    *)
      note_fail "$rel: unrecognised template extension"
      ;;
  esac
done < <(find "$TEMPLATES" -type f | LC_ALL=C sort)

# Coverage gate: ensure all six rubric languages have at least one
# template directory present. Catches accidental directory deletion.
for lang in python javascript typescript rust ruby go; do
  if [[ ! -d "$TEMPLATES/$lang" ]]; then
    note_fail "templates/$lang/ missing — rubric coverage broken"
  else
    note_pass
  fi
done

if (( FAIL == 0 )); then
  echo "templates.test.sh: PASS — $PASS checks"
  exit 0
else
  echo "templates.test.sh: FAIL — $PASS passed, $FAIL failed" >&2
  for msg in "${FAILURES[@]}"; do
    echo "  - $msg" >&2
  done
  exit 1
fi
