#!/usr/bin/env bash
# generate-cases.sh — materialises cases.json with expected values derived
# from the v1.x enforce-ownership.sh perl substitution chain (invariant C
# of the v2.0 migration ticket).
#
# Run this script once when defining new fixture cases or when the canonical
# perl chain in bin/strip-trailers.sh genuinely changes. The committed
# cases.json is the regression bar — drift between bin/strip-trailers.sh
# and these expected values is a ship-blocker, not a fixture-update prompt.

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "FATAL: jq required" >&2
  exit 2
fi
if ! command -v perl >/dev/null 2>&1; then
  echo "FATAL: perl required" >&2
  exit 2
fi

# The v1.x enforce-ownership.sh perl chain — verbatim. Do not edit; the
# committed cases.json has its expected values pinned to this exact chain.
strip_v1() {
  printf '%s\n' "$1" | perl -pe '
    s/[Cc]o-[Aa]uthored-[Bb]y:[^"\x27\\]*//g;
    s/.*[Gg]enerated (?:with|by).*[Cc]laude[^"\x27\\]*//g;
  ' | cat -s
}

# ----- inputs ---------------------------------------------------------

input_single_coauthor=$'fix(x): test\n\nCo-Authored-By: Claude <noreply@anthropic.com>'

input_multi_coauthor=$'fix(y): pair work\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-Authored-By: Other <other@example.com>'

input_generated_with=$'feat(z): add thing\n\n\xf0\x9f\xa4\x96 Generated with Claude Code'

input_generated_by=$'docs(a): update docs\n\nGenerated by Claude'

input_trailer_and_footer=$'fix(b): bugfix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n\n\xf0\x9f\xa4\x96 Generated with Claude Code'

input_lowercase_coauthor=$'chore(c): cleanup\n\nco-authored-by: claude <noreply@anthropic.com>'

input_pr_body_markdown=$'## Summary\n- Adds the X feature\n\n## Test plan\n- [x] Manual test\n\n\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/claude-code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>'

input_already_clean=$'feat(clean): no attribution at all\n\nThis is a clean message with no automated trailers or footers.'

input_crlf=$'fix(crlf): test\r\nCo-Authored-By: Claude <noreply@anthropic.com>\r\n'

# ----- emit cases.json -----------------------------------------------

emit_case() {
  local name="$1" input="$2" expected
  expected=$(strip_v1 "$input")
  jq -n --arg n "$name" --arg i "$input" --arg e "$expected" \
    '{name: $n, input: $i, expected: $e}'
}

cases_json=$(jq -s '.' <(
  emit_case "single-coauthor"            "$input_single_coauthor"
  emit_case "multi-coauthor"             "$input_multi_coauthor"
  emit_case "generated-with-claude-code" "$input_generated_with"
  emit_case "generated-by-claude"        "$input_generated_by"
  emit_case "trailer-and-footer"         "$input_trailer_and_footer"
  emit_case "lowercase-coauthor"         "$input_lowercase_coauthor"
  emit_case "pr-body-markdown"           "$input_pr_body_markdown"
  emit_case "already-clean"              "$input_already_clean"
  emit_case "crlf-line-endings"          "$input_crlf"
))

OUT="$(dirname "$(realpath "$0")")/cases.json"
printf '%s\n' "$cases_json" > "$OUT"
echo "Wrote $OUT ($(jq 'length' <<<"$cases_json") cases)"
